### ISSUE TITLE
Damp Diary Location

### ISSUE THREAD

**Issue by hseager** [Nickswoboda/all-ears-unturned#1]
For No Stone Unturned it says the Damp Diary is in Act1 - The Cavern of Anger, when it's actually in Merveil's Lair. 

It might be more clear to change the location to Merveil's Lair to save people searching for it in The Cavern of Anger (like I did :)).

Cheers

**Comment by Nickswoboda** [comment]
Thank you for your feedback. I updated the 'No Stone Unturned' guide appropriately for that lore item. I did the same for various other locations such as the Eternal Laboratory. Please let me know if I have missed anything.
