### ISSUE TITLE
Misleading instructions

### ISSUE THREAD

**Issue by eirc** [Nickswoboda/all-ears-unturned#10]
https://github.com/Nickswoboda/all-ears-unturned/blob/cad6c2375fb5e0324dd0f439df734eb78b18c106/all-ears-unturned/assets/steps.json#L1474

Where do find Nessa here? Does she appear in the Abberath side area? I only recalled the earlier appearance at the eye of conquest and the later one at the black flag so I run to that one and bricked my run :'( I'd suggest you add some description like "she's next to abberath".

**Comment by Nickswoboda** [comment]
v1.3.0 added a note indicating that Nessa is located in the Prisoner's Gate's canyons.
