### ISSUE TITLE
Step 158 Fairgraves spawn

### ISSUE THREAD

**Issue by Quakstab** [Nickswoboda/all-ears-unturned#12]
Fairgraves will not spawn in Docks if "The Marooned Mariner" (Allflame) Quest is not completed.
It would be good to add the Quest into the steps at a place where it is save to do it without loosing dialog options.

**Comment by Nickswoboda** [comment]
v1.3.0 added notes that you can complete side quests after each act. As the Marooned Mariner is a Skill Point quest, I believe it shouldn't be much of an issue. However, if it is still a problem, I will make a note of it in the step.
