### ISSUE TITLE
Step 438 Talking to Sin about Garukhan

### ISSUE THREAD

**Issue by Quakstab** [Nickswoboda/all-ears-unturned#13]
After killing Garukhan and collecting the Feather it is needed to go to Highgate and Talk with Sin (not in Quarry as the red text says)

**Comment by Nickswoboda** [comment]
It may technically be possible to also complete the dialog by talking to Sin in Highgate, but I confirmed you can complete the dialog by talking to him in the Quarry(where you killed Garukhan).
