### ISSUE TITLE
Tweaks

### ISSUE THREAD

**Issue by Loftaris** [Nickswoboda/all-ears-unturned#3]
Forgive me if this is the wrong place to put this, I'm very new to GitHub.

1) For the overlay, it would be much more friendly if the < > arrows were at the top, not the bottom, the top never moves, but the bottom depending on if it has 1:6 tasks, the < > arrows won't be in the same spot.  Yes, I know there's QW to cycle through them, but that leads me to my second point.

2) PLEASE REMOVE QW!!!!!!!!!  How many times I've checked a box, only to press either Q or W to attack something coming for me, and have it scroll back 20-30 pages.  Beyond frustrating!

3) could you possibly rearrange a few of these to follow the same order.  In all ears, you have me go to the crypt first to rescue Helena, but in No Stone, you have me go to Fellshrine first, then go back to the crypt.

4) This is mostly for newer players (or boneheads like me), can you possibly add even a generic message to say when it's okay to do things like collect quest rewards (for example, the deep dweller in the submerged passage, not 100% certain if it'll screw things up, I just skipped it for now)

5) Thanks for the tool, I've completely ignore this because I've tried many times in the past but always missed something.  I'm halfway through and on track.

**Comment by Nickswoboda** [comment]
I just released v1.1.5 which addresses some of your concerns. The navigation arrows have been moved towards the top, and I have added an option in the settings menu to disable the hotkeys. I have also re-arranged the order of the No Stone Unturned steps to better align with All Ears. 

I will try to come up with a way to address point #4, but until then I would just err on the side of caution. Once you finish an Act, you can complete any other side quest without it affected your progress.

Thanks a lot for your feedback.

**Comment by Loftaris** [comment]
Well you already addressed your own point #4.  Just by adding a message when it shows "You should have # of # completed by now"  You could also have a message saying "It is now safe to complete any side quests before moving forward to act BLAH"
