### ISSUE TITLE
Missing 1

### ISSUE THREAD

**Issue by Loftaris** [Nickswoboda/all-ears-unturned#4]
I just finished, I wsa at 493/505 when I reached step 479.  I completed all the prophecies in order, first rank 1, then rank v, got the keys, killed the pale court, and now I'm sitting at 504/505 completion, and I can't seem to find the last one.

Is there something missing?  Did I somehow miss a step somewhere?

**Comment by Nickswoboda** [comment]
Navali has 12 prophecy related dialogs. If you were indeed at 493, those 12 would put you at 505. Talk to Navali in game and make sure all 12 show up greyed-out. If one is missing try completing the rank 1 of that propechy. 
If that doesn't work it means you most likely missed one while going through the storyline. Did you happen to complete any prophecies before beating act 10?

**Comment by Loftaris** [comment]
No. It was a brand new character purely for this challenge.  I followed it
pretty strictly even skipping skill point quests etc.

I'm fairly sure I didn't miss any Navali quests but that's about the only
possible thing it may be.  I'll check again when I have time.

Thank you.

**Comment by Loftaris** [comment]
You were absolutely correct, and your tool is awesome.  I somehow missed Plaguemaw.  I have now finished All Ears :D
