### ISSUE TITLE
Missing dialouge act 1

### ISSUE THREAD

**Issue by TimSundt** [Nickswoboda/all-ears-unturned#7]
Hi, just started using this. It seems to skip anything related to The dweller of the deep sidequest.

**Comment by TimSundt** [comment]
Also missing Yeena  dialouge on brutus

**Comment by Nickswoboda** [comment]
The All Ears achievement description is weird because it doesn't actually require you to listen to every single dialog option that exists. There are plenty of dialog options that you will find that don't make any difference in the progress of the achievement. This tool only tracks the dialog options that are actually required for to complete the achievement, so it is expected that some options are missing. After each act it will tell you how many out of 505 dialogs you should have for the achievement up to that point. If you're missing some then, please let me know, but I ran through it in the beginning of the league and it worked fine.

**Comment by TimSundt** [comment]
> The All Ears achievement description is weird because it doesn't actually require you to listen to every single dialog option that exists. There are plenty of dialog options that you will find that don't make any difference in the progress of the achievement. This tool only tracks the dialog options that are actually required for to complete the achievement, so it is expected that some options are missing. After each act it will tell you how many out of 505 dialogs you should have for the achievement up to that point. If you're missing some then, please let me know, but I ran through it in the beginning of the league and it worked fine.

Ok, ty for the info. Ill try to note if I see something missing. Anyways great tool ty for making it easier :)

**Comment by TimSundt** [comment]
Sry, followed the guide every step but when it says 260 mine is at 259 at the end of act 4. Im pretty sure I did everything right, any idea what couldve been missed?

**Comment by Nickswoboda** [comment]
I think the main one's in Act 4 that are somewhat easy to miss are the one's where you have to wait before progressing through areas, like talking to Piety before going to the Harvest or talking to Dialla after finding the organs but before killing Malachai. You can try just talking to everyone in Act 4 again to see if you missed anything. If not, you unfortunately must have just accidently missed something. I'm really sorry the tool didn't work for you, I know the achievement is a huge pain in the ass and sucks to have to restart.

**Comment by TimSundt** [comment]
> I think the main one's in Act 4 that are somewhat easy to miss are the one's where you have to wait before progressing through areas, like talking to Piety before going to the Harvest or talking to Dialla after finding the organs but before killing Malachai. You can try just talking to everyone in Act 4 again to see if you missed anything. If not, you unfortunately must have just accidently missed something. I'm really sorry the tool didn't work for you, I know the achievement is a huge pain in the ass and sucks to have to restart.

It sucks, but at least the no stone unturned is gonna work out. Plus for this time I was just trying to learn the lore anyway. Next tiime I wanna try I can atleast speed run it while using your checklist :)

**Comment by Nickswoboda** [comment]
[v1.2.0](https://github.com/Nickswoboda/all-ears-unturned/releases/tag/v1.2.0) has been released which will hopefully improve the experience. See this [comment](https://github.com/Nickswoboda/all-ears-unturned/issues/6#issuecomment-825325880) for details.
