### ISSUE TITLE
I can has labyrinth?

### ISSUE THREAD

**Issue by Ambient-Impact** [Nickswoboda/all-ears-unturned#8]
I'm partway through act 3 at the moment and wondering if it's safe to do the labyrinth at all or if I have to wait until later?

**Comment by Nickswoboda** [comment]
I have not tested it, but I do not believe the lab has any impact on the completion of the achievement so you should be fine. Please let me know if it somehow affected the progress.

As a side note, I would be careful during Act 3. There have been reports of potentially missing dialogs (#7), that I haven't had a chance to check out myself yet. Be sure not to have quest items when talking to Fairgraves or Dialla until you're instructed to. Hopefully the guide will work for you.

**Comment by Ambient-Impact** [comment]
Will do, thanks!
