### ISSUE TITLE
All Ears - Act 1, Bestel on Brutus

### ISSUE THREAD

**Issue by caseg1** [Nickswoboda/all-ears-unturned#9]
Step 28 says talk to Bestel about Brutus after entering the Lower Prison, but that option isn't available. 
[Here is a steam screenshot](https://steamuserimages-a.akamaihd.net/ugc/1779463159041624825/F50344D1368ABD794CFFB9C19A9C402BF3A677A0/) after using the waypoint in the Lower Prison back to town and attempting to talk to Bestel. I believe you have to talk to Tarkleigh first.

**Comment by Nickswoboda** [comment]
Thanks for the report. v1.3.0 added a note indicating that Tarkleigh needs to be talked to first.
